Whisper/scottg notebook
graphcore/optimum-graphcore-fork pull request #21
Opened 2023-04-06 16:09 UTC by scott-griffiths

Rewriting Whisper inference notebook.

Adding explanatory text, refactoring code, adding multimedia features and updating for new optimum-graphcore version.
Tested with optimum-graphcore 0.6.0.

2023-04-06 16:12 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/optimum-graphcore/pr_21). All of your documentation changes will be reflected on that endpoint.

2023-04-07 09:14 UTC, jayniep-gc requested changes
I've made my changes with the main aim of being clearer for the user. Please let me know if anything in what I've done is not clear. 

There is a problem with GitHub. When I try to add comments to anything that appears after a figure, an image is marked for replacement even though this is not intended. The last few comments have this and the changed text is not highlighted...

2023-04-07 09:14 UTC, jayniep-gc commented on notebooks/whisper-example.ipynb
> +    "There will typically be some small differences, but even the 'tiny' Whisper model does a great job, and also adds in punctuation.\n",
```suggestion
    "There will typically be some small differences, but even 'whisper-tiny' does a great job! It even adds punctuation.\n",
```

2023-04-07 09:14 UTC, jayniep-gc commented on notebooks/whisper-example.ipynb
> +    "You can compare with the audio itself using the controls underneath."
```suggestion
    "You can listen to the audio and compare the model result yourself using the controls below."
```

2023-04-07 09:14 UTC, jayniep-gc commented on notebooks/whisper-example.ipynb
> +       "                    <source src=\"data:audio/wav;base64,UklGRsQYBgBXQVZFZm10IBAAAAABAAEAgD4AAAB9AAACABAAZGF0YaAYBgDb/wMAHAA5ADAAKAA+AC0A+//s/9j/7v8cAAsA5/8QABoA5P/w/yMA9f/p/wYA7P/1/zIAEgDd//H
```suggestion
    "The model only needs to be compiled once. Subsequent inferences will be much faster.\n",
```

2023-04-07 09:14 UTC, jayniep-gc commented on notebooks/whisper-example.ipynb
> +       "                    <source src=\"data:audio/wav;base64,UklGRsQYBgBXQVZFZm10IBAAAAABAAEAgD4AAAB9AAACABAAZGF0YaAYBgDb/wMAHAA5ADAAKAA+AC0A+//s/9j/7v8cAAsA5/8QABoA5P/w/yMA9f/p/wYA7P/1/zIAEgDd//H
I'm not sure why GitHub marks the image for deletion. 😞

2023-04-07 09:14 UTC, jayniep-gc commented on notebooks/whisper-example.ipynb
> +       "                    <source src=\"data:audio/wav;base64,UklGRsQYBgBXQVZFZm10IBAAAAABAAEAgD4AAAB9AAACABAAZGF0YaAYBgDb/wMAHAA5ADAAKAA+AC0A+//s/9j/7v8cAAsA5/8QABoA5P/w/yMA9f/p/wYA7P/1/zIAEgDd//H
```suggestion
    "## Next steps\n",
```

2023-04-07 09:14 UTC, jayniep-gc commented on notebooks/whisper-example.ipynb
> +       "                    <source src=\"data:audio/wav;base64,UklGRsQYBgBXQVZFZm10IBAAAAABAAEAgD4AAAB9AAACABAAZGF0YaAYBgDb/wMAHAA5ADAAKAA+AC0A+//s/9j/7v8cAAsA5/8QABoA5P/w/yMA9f/p/wYA7P/1/zIAEgDd//H
```suggestion
    "The `whisper-tiny` model used here is very fast for inference and cheap to run, but its accuracy can be improved.\n",
```

2023-04-07 09:14 UTC, jayniep-gc commented on notebooks/whisper-example.ipynb
> +       "                    <source src=\"data:audio/wav;base64,UklGRsQYBgBXQVZFZm10IBAAAAABAAEAgD4AAAB9AAACABAAZGF0YaAYBgDb/wMAHAA5ADAAKAA+AC0A+//s/9j/7v8cAAsA5/8QABoA5P/w/yMA9f/p/wYA7P/1/zIAEgDd//H
```suggestion
    "The `whisper-base` and `whisper-small` models have 74M and 244M parameters respectively (compared to just 39M for `whisper-tiny`). You can try out `whisper-base` by using `model_spec = \"openai/whisper-base.en\"` or `whisper-small` by using `model_spec = \"openai/whisper-small.en\"` near the start of this notebook.\n",
```

2023-04-07 09:14 UTC, jayniep-gc commented on notebooks/whisper-example.ipynb
> +       "                    <source src=\"data:audio/wav;base64,UklGRsQYBgBXQVZFZm10IBAAAAABAAEAgD4AAAB9AAACABAAZGF0YaAYBgDb/wMAHAA5ADAAKAA+AC0A+//s/9j/7v8cAAsA5/8QABoA5P/w/yMA9f/p/wYA7P/1/zIAEgDd//H
Add a link for the contact Graphcore. Other notebooks refer to the Graphcore Slack Community so maybe that would be suitable here.

```suggestion
    "To run these you will need more than the IPU-POD4. On Paperspace this is available using either an IPU-POD16 or a Bow Pod16 machine. Please contact Graphcore if you need assistance running these larger models.\n"
```

2023-04-07 09:14 UTC, jayniep-gc commented on notebooks/whisper-example.ipynb
> +       "                    <source src=\"data:audio/wav;base64,UklGRsQYBgBXQVZFZm10IBAAAAABAAEAgD4AAAB9AAACABAAZGF0YaAYBgDb/wMAHAA5ADAAKAA+AC0A+//s/9j/7v8cAAsA5/8QABoA5P/w/yMA9f/p/wYA7P/1/zIAEgDd//H
```suggestion
    "We used the Optimum Graphcore package to interface between the IPU and the Hugging Face Transformers library. This meant that only a few lines of code were needed to get this state-of-the-art automated speech recognition model running on IPUs."
```

2023-04-11 12:48 UTC, jayniep-gc commented on notebooks/whisper-example.ipynb
> +    "In order to run this notebook you will need to be in an environment with the Poplar SDK installed and enabled - on Paperspace this is handled by default.\n",
```suggestion
    "In order to run this notebook you will need to be in an environment with the Poplar SDK installed and enabled. This is done by default on Paperspace. If you are not using Paperspace, refer to the [getting started guide](https://docs.graphcore.ai/en/latest/getting-started.html#getting-started) for your system for a description of how to set this up.\n",
```

2023-04-11 12:50 UTC, jayniep-gc reviewed
Phrasing improvement to conclusion

2023-04-11 13:00 UTC, jayniep-gc reviewed
Fixing Join Slack link

2023-04-11 16:25 UTC, closed without merging

2023-04-11 16:28 UTC, payoto commented
Closed in favour of an upstream PR https://github.com/huggingface/optimum-graphcore/pull/312